---
name: Self test

on: push

jobs:
    test:
        name: Self test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code of this repo
              uses: actions/checkout@v2
              with:
                  path: WebImblaze-Selenium

            - name: What is the current folder
              run: pwd

            - name: Checkout WebImblaze
              uses: actions/checkout@master
              with:
                  repository: Qarj/WebImblaze
                  path: WebImblaze

            - name: What is the current folder
              run: pwd

            - name: Where is HOME
              run: echo $HOME

            - name: Where is GITHUB_WORKSPACE
              run: echo $GITHUB_WORKSPACE

            - name: All files in $HOME
              run: ls -asl $HOME

            - name: All files in $HOME/work
              run: ls -asl $HOME/work

            - name: All files in $HOME/work/WebImblaze-Selenium
              run: ls -asl $HOME/work/WebImblaze-Selenium

            - name: All files in $GITHUB_WORKSPACE
              run: ls -asl $GITHUB_WORKSPACE

            - name: All files in $GITHUB_WORKSPACE/WebImblaze
              run: ls -asl $GITHUB_WORKSPACE/WebImblaze

            - name: All files in $GITHUB_WORKSPACE/WebImblaze-Selenium
              run: ls -asl $GITHUB_WORKSPACE/WebImblaze-Selenium

            - name: Setup Perl
              uses: shogo82148/actions-setup-perl@v1
              with:
                  install-modules-with: cpanm
                  install-modules-args: --with-develop --with-configure

            - name: Install LWP::Protocol::https
              run: cpanm LWP::Protocol::https

            - name: Install XML::Simple
              run: cpanm XML::Simple

            - name: Install Selenium::Remote::Driver
              run: cpan Selenium::Remote::Driver

            - name: Check Perl version
              run: perl --version

            - name: Run update.pl to move WebImblaze-Selenium plugin into WebImblaze
              run: perl $GITHUB_WORKSPACE/WebImblaze-Selenium/plugins/update.pl

            - name: Check WebImblaze version
              run: perl $GITHUB_WORKSPACE/WebImblaze/wi.pl --version

            - name: Self test WebImblaze
              run: perl $GITHUB_WORKSPACE/WebImblaze/wi.pl selftest/all_core.test

            - name: Make selenium folder
              run: mkdir $HOME/selenium

            - name: Download latest release of chromedriver version string
              run: wget http://chromedriver.storage.googleapis.com/LATEST_RELEASE -O $HOME/selenium/LATEST_RELEASE

            - name: Set env variable of latest release
              run: latest=$(cat $HOME/selenium/LATEST_RELEASE) && echo $latest && echo "latest=$latest" >> $GITHUB_ENV

            - name: Can we access it as latest?
              run: echo $latest

            - name: Download the latest release of chromedriver
              run: wget -N "https://chromedriver.storage.googleapis.com/${{ env.latest }}/chromedriver_linux64.zip" -O chromedriver_linux64.zip

            - name: Unzip chromedriver
              run: unzip -o chromedriver_linux64.zip -d .

            - name: Run chromedriver binary to check version
              run: ./chromedriver --version

            - name: Download latest Selenium Standalone 3 Server
              run: wget -N https://bit.ly/2TlkRyu -O selenium-server-3-standalone.jar

            - name: Check Java and Selenium Standalone versions
              run: java -version && java -jar $HOME/selenium/selenium-server-3-standalone.jar --version

            - name: Install OpenJDK 8
              uses: actions/setup-java@v2
              with:
                  distribution: "zulu"
                  java-version: "8"

            - name: Install Google Chrome
              uses: browser-actions/setup-chrome@latest
              with:
                  chrome-version: stable

            - name: Check Chrome version
              run: chrome --version

            - name: Archive test report
              if: always()
              uses: actions/upload-artifact@v2
              with:
                  name: html-results-report
                  path: output/Results.html

            - name: Zip main test output
              if: always()
              run: zip -r output-main.zip output

            - name: Archive main test output
              if: always()
              uses: actions/upload-artifact@v2
              with:
                  name: main-test-output
                  path: output-main.zip

            - name: Zip substeps test output
              if: always()
              run: zip -r output-substeps.zip selftest/output

            - name: Archive substeps test output
              if: always()
              uses: actions/upload-artifact@v2
              with:
                  name: substeps-test-output
                  path: output-substeps.zip
